"""
${{ values.name }} — ${{ values.description }}
Generated by the Developer Platform Golden Path template.
"""

import os
import time
import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST
from starlette.requests import Request
from starlette.responses import Response

from opentelemetry import trace
from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanExporter
from opentelemetry.sdk.resources import Resource
from opentelemetry.semconv.resource import ResourceAttributes

# ---------------------------------------------------------------------------
# Telemetry Setup
# ---------------------------------------------------------------------------

resource = Resource.create({
    ResourceAttributes.SERVICE_NAME: "${{ values.name }}",
    ResourceAttributes.SERVICE_VERSION: "0.1.0",
})

provider = TracerProvider(resource=resource)
otlp_endpoint = os.getenv("OTEL_EXPORTER_OTLP_ENDPOINT", "localhost:4317")
exporter = OTLPSpanExporter(endpoint=otlp_endpoint, insecure=True)
provider.add_span_processor(BatchSpanExporter(exporter))
trace.set_tracer_provider(provider)
tracer = trace.get_tracer(__name__)

# Prometheus Metrics
REQUEST_COUNT = Counter(
    "http_requests_total",
    "Total HTTP requests",
    ["method", "endpoint", "status"],
)
REQUEST_LATENCY = Histogram(
    "http_request_duration_seconds",
    "HTTP request latency",
    ["method", "endpoint"],
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("${{ values.name }}")


@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("Starting ${{ values.name }}")
    yield
    provider.shutdown()
    logger.info("${{ values.name }} shut down")


app = FastAPI(
    title="${{ values.name }}",
    description="${{ values.description }}",
    version="0.1.0",
    lifespan=lifespan,
)


# ---------------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------------

@app.middleware("http")
async def metrics_middleware(request: Request, call_next):
    start = time.time()
    response = await call_next(request)
    duration = time.time() - start
    endpoint = request.url.path
    REQUEST_COUNT.labels(request.method, endpoint, response.status_code).inc()
    REQUEST_LATENCY.labels(request.method, endpoint).observe(duration)
    return response


# ---------------------------------------------------------------------------
# Health & Metrics
# ---------------------------------------------------------------------------

@app.get("/healthz")
async def healthz():
    return {"status": "healthy", "service": "${{ values.name }}"}


@app.get("/readyz")
async def readyz():
    return {"status": "ready"}


@app.get("/metrics")
async def metrics():
    return Response(content=generate_latest(), media_type=CONTENT_TYPE_LATEST)


# ---------------------------------------------------------------------------
# API Routes — Add your business logic below
# ---------------------------------------------------------------------------

class HelloResponse(BaseModel):
    message: str
    version: str


@app.get("/api/v1/hello", response_model=HelloResponse)
async def hello():
    with tracer.start_as_current_span("hello"):
        return HelloResponse(
            message="Hello from ${{ values.name }}!",
            version="0.1.0",
        )
