/**
 * ${{ values.name }} — ${{ values.description }}
 * Generated by the Developer Platform Golden Path template.
 *
 * High-performance C++ microservice with embedded HTTP server.
 */

#include <iostream>
#include <string>
#include <csignal>
#include <atomic>
#include <cstring>
#include <sstream>
#include <thread>
#include <chrono>

// Simple socket-based HTTP (see services/pricing-engine for full example)
#ifdef _WIN32
  #include <winsock2.h>
  #pragma comment(lib, "ws2_32.lib")
#else
  #include <sys/socket.h>
  #include <netinet/in.h>
  #include <unistd.h>
#endif

static std::atomic<bool> running{true};

void signal_handler(int) { running = false; }

std::string json_response(int code, const std::string& body) {
    std::ostringstream oss;
    oss << "HTTP/1.1 " << code << " OK\r\n"
        << "Content-Type: application/json\r\n"
        << "Content-Length: " << body.size() << "\r\n"
        << "\r\n" << body;
    return oss.str();
}

int main() {
    std::signal(SIGINT, signal_handler);
    std::signal(SIGTERM, signal_handler);

    int port = ${{ values.port }};
    if (const char* env_p = std::getenv("PORT")) {
        port = std::stoi(env_p);
    }

    int server_fd = socket(AF_INET, SOCK_STREAM, 0);
    int opt = 1;
    setsockopt(server_fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));

    struct sockaddr_in addr{};
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = INADDR_ANY;
    addr.sin_port = htons(port);

    bind(server_fd, (struct sockaddr*)&addr, sizeof(addr));
    listen(server_fd, 128);

    std::cout << "${{ values.name }} v0.1.0 listening on port " << port << std::endl;

    while (running) {
        int client = accept(server_fd, nullptr, nullptr);
        if (client < 0) continue;

        char buffer[4096] = {};
        read(client, buffer, sizeof(buffer) - 1);
        std::string request(buffer);

        std::string response;
        if (request.find("GET /healthz") != std::string::npos) {
            response = json_response(200, R"({"status":"healthy","service":"${{ values.name }}"})");
        } else if (request.find("GET /readyz") != std::string::npos) {
            response = json_response(200, R"({"status":"ready"})");
        } else if (request.find("GET /api/v1/hello") != std::string::npos) {
            response = json_response(200, R"({"message":"Hello from ${{ values.name }}!","version":"0.1.0"})");
        } else {
            response = json_response(404, R"({"error":"not found"})");
        }

        write(client, response.c_str(), response.size());
        close(client);
    }

    close(server_fd);
    std::cout << "${{ values.name }} shut down" << std::endl;
    return 0;
}
