apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: ${{ values.port }}
      targetPort: ${{ values.port }}
      protocol: TCP
  selector:
    app: ${{ values.name }}
