/**
 * ${{ values.name }} — ${{ values.description }}
 * Generated by the Developer Platform Golden Path template.
 */

import './tracing';
import express, { Request, Response } from 'express';
import helmet from 'helmet';
import cors from 'cors';
import compression from 'compression';
import { register, collectDefaultMetrics, Counter, Histogram } from 'prom-client';
import { createLogger, format, transports } from 'winston';

const logger = createLogger({
  level: 'info',
  format: format.combine(format.timestamp(), format.json()),
  defaultMeta: { service: '${{ values.name }}' },
  transports: [new transports.Console()],
});

collectDefaultMetrics();

const httpRequests = new Counter({
  name: 'http_requests_total',
  help: 'Total HTTP requests',
  labelNames: ['method', 'path', 'status'],
});

const httpLatency = new Histogram({
  name: 'http_request_duration_seconds',
  help: 'HTTP request latency',
  labelNames: ['method', 'path'],
  buckets: [0.01, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5],
});

const app = express();
app.use(helmet());
app.use(cors());
app.use(compression());
app.use(express.json());

// Metrics middleware
app.use((req: Request, res: Response, next) => {
  const start = Date.now();
  res.on('finish', () => {
    const duration = (Date.now() - start) / 1000;
    httpRequests.inc({ method: req.method, path: req.route?.path || req.path, status: res.statusCode });
    httpLatency.observe({ method: req.method, path: req.route?.path || req.path }, duration);
  });
  next();
});

// Health
app.get('/healthz', (_req: Request, res: Response) => {
  res.json({ status: 'healthy', service: '${{ values.name }}' });
});
app.get('/readyz', (_req: Request, res: Response) => {
  res.json({ status: 'ready' });
});

// Metrics
app.get('/metrics', async (_req: Request, res: Response) => {
  res.set('Content-Type', register.contentType);
  res.end(await register.metrics());
});

// API Routes — Add your business logic below
app.get('/api/v1/hello', (_req: Request, res: Response) => {
  res.json({ message: 'Hello from ${{ values.name }}!', version: '0.1.0' });
});

const port = process.env.PORT || ${{ values.port }};
app.listen(port, () => {
  logger.info(`${{ values.name }} listening on port ${port}`);
});

export default app;
